# Producers
${COMPUTE_NODES_LINE}

# update policies
updtr_add name=update_all interval=1000000 auto_interval=true
updtr_prdcr_add name=update_all regex=.*
updtr_start name=update_all

# csv configs
load name=store_csv
config name=store_csv path=/root/storage buffer=0
strgp_add name=meminfo-store plugin=store_csv container=memory_metrics schema=meminfo
strgp_add name=vmstat-store plugin=store_csv container=system_metrics schema=vmstat
strgp_start name=meminfo-store
strgp_start name=vmstat-store
