# load name=meminfo
# config name=meminfo producer=${HOSTNAME} instance=${HOSTNAME}/meminfo component_id=1
# start name=meminfo interval=1000000

# load name=vmstat
# config name=vmstat producer=${HOSTNAME} instance=${HOSTNAME}/vmstat component_id=2
# start name=vmstat interval=1000000

# prdcr_add name=agg host=${AGG_HOST} type=active xprt=sock port=411
# prdcr_start name=agg

load name=meminfo
config name=meminfo producer=${HOSTNAME} instance=${HOSTNAME}/meminfo component_id=1
start name=meminfo interval=1000000

load name=vmstat
config name=vmstat producer=${HOSTNAME} instance=${HOSTNAME}/vmstat component_id=2
start name=vmstat interval=1000000
